name: Azure IPAM Build

run-name: Azure IPAM Production Container Build

on:
  push:
    branches: [ fix/ipam-issue ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Update Azure IPAM Containers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Azure IPAM Code
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            engine
            ui
            lb

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image engine
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./engine
          file: ./engine/Dockerfile.deb
          push: true
          tags: pmorisseau/ipam-engine:latest

      - name: Build and push Docker image function
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./engine
          file: ./engine/Dockerfile.func
          push: true
          tags: pmorisseau/ipam-func:latest

      - name: Build and push Docker image UI
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./ui
          file: ./ui/Dockerfile.deb
          push: true
          tags: pmorisseau/ipam-ui:latest

      - name: Build and push Docker image LB
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./lb
          file: ./lb/Dockerfile
          push: true
          tags: pmorisseau/ipam-lb:latest
